import type { DateStr, TimeStr } from '@/types/entities'
import type { EventSource, Priority } from '@/types/enums'
import type { CommandIntentKind, EntityRef } from '@/services/commands/intents'

/**
 * What a model is allowed to say, and what it is allowed to propose.
 *
 * The governing idea of M15: **the model is an untrusted external component.**
 * It is not a privileged actor with a shortcut into the database; it is a
 * process that returns text, and this file describes the very small shape that
 * text is permitted to take before anything else in Vaultwork will look at it.
 *
 * Three properties are load-bearing, and each is a type rather than a promise:
 *
 *  1. **A proposal is not a command.** `ProposedIntent` deliberately is not
 *     `CommandIntent`. It names the same *kinds*, so M15.4 can translate one
 *     into the other, but it carries none of the fields only the application
 *     may fill in — no `taskId`, no `TaskDraft`, no `QuickAddToken` offsets.
 *
 *  2. **A model cannot name a row.** `AiRef` is the text half of `EntityRef`
 *     and nothing else, so `{ by: 'id' }` is not merely rejected at runtime —
 *     it cannot be constructed. Turning "Java revision" into an id is
 *     `entityResolver`'s job in M15.4, against rows that actually exist.
 *
 *  3. **A model cannot say who it is.** `source` is fixed to `'ai'` and set by
 *     the parser. The model does not get a vote on how its own output is
 *     attributed in the event log.
 *
 * Nothing here executes, resolves, queries or persists. This module is types
 * and constants; the only runtime code in `src/ai` is the parser that enforces
 * them.
 */

/**
 * The one reference shape a model may produce.
 *
 * Written as a restriction of the real `EntityRef` rather than a lookalike, so
 * the day someone widens `EntityRef` this either still compiles as a subset or
 * fails loudly here.
 */
export type AiRef = Extract<EntityRef, { by: 'text' }>

/**
 * The intents a model may propose, as of M15.2.
 *
 * Deliberately three of the roughly sixty `CommandIntent` kinds. The set is an
 * allowlist rather than a denylist because the safe list is the short one: a
 * new intent kind added anywhere else in the application must not silently
 * become something a model can ask for.
 *
 * `task.update` is **not** here, and its absence is a design decision rather
 * than an oversight. `Intent<'task.update'>` requires a `taskId: Id` — a real
 * database id — and a model that could supply one would be inventing rows. The
 * safe version of "change this task" is a resolved reference, which is M15.4's
 * work; until then the narrower set is the correct set.
 *
 * Every destructive kind is absent for the obvious reason.
 */
export const AI_ALLOWED_INTENT_KINDS = ['task.add', 'task.complete', 'task.reschedule'] as const

export type AiIntentKind = (typeof AI_ALLOWED_INTENT_KINDS)[number]

/**
 * Compile-time proof that the allowlist names real commands.
 *
 * If a kind here is renamed or removed in `intents.ts`, this stops compiling
 * rather than failing at runtime in front of a user.
 */
const _allowlistNamesRealCommands: readonly CommandIntentKind[] = AI_ALLOWED_INTENT_KINDS
void _allowlistNamesRealCommands

/**
 * The half of `IntentBase` the application owns.
 *
 * Mirrors the `CommandIntent` contract so M15.4's translation is a spread
 * rather than a re-derivation — but both fields are written by the parser, and
 * a model that supplies either is rejected for an unknown field.
 */
interface ProposedBase {
  /** Always `'ai'`. The model does not choose how it is attributed. */
  readonly source: Extract<EventSource, 'ai'>
  /** The user's original request, per the `CommandIntent` contract. */
  readonly raw: string
}

type Proposed<K extends AiIntentKind, P = object> = ProposedBase & { kind: K } & P

/**
 * A single thing a model proposes doing.
 *
 * Note what `task.add` carries: the fields a person could have typed into Quick
 * Add, and not a `TaskDraft`. Building the draft — and the token offsets that
 * go with it — is the application's job, because those describe *where in the
 * user's own text* something was parsed from, and a model has no such text.
 */
export type ProposedIntent =
  | Proposed<
      'task.add',
      {
        title: string
        dueDate: DateStr | null
        dueTime: TimeStr | null
        priority: Priority
        /** A name, never a project id. Resolved in a later phase. */
        projectName: string | null
        estimateMin: number | null
      }
    >
  | Proposed<'task.complete', { ref: AiRef }>
  | Proposed<'task.reschedule', { ref: AiRef; dueDate: DateStr | null; dueTime: TimeStr | null }>

/**
 * One step of a proposed plan.
 *
 * `id` is local to this proposal — `step-1`, `step-2` — and is generated by the
 * parser after validation. It exists so a later phase's UI can say "apply steps
 * 1 and 3", and it is deliberately not anything a model supplied: a
 * model-chosen identifier that looked like a row id would be exactly the
 * confusion this layer exists to prevent.
 */
export interface AiStep {
  id: string
  description: string
  intent: ProposedIntent
}

/**
 * Everything a model is allowed to reply.
 *
 * Three cases, because there are three honest outcomes: it knows the answer, it
 * needs to ask, or it wants to change something. A plan is a *proposal* — in
 * M15.2 nothing executes it, and in M15.5 nothing will execute it without the
 * user saying so.
 */
export type AiResponse =
  | { kind: 'answer'; message: string }
  | { kind: 'clarification'; message: string; options: string[] }
  | { kind: 'plan'; message: string; steps: AiStep[] }

export type AiResponseKind = AiResponse['kind']

export const AI_RESPONSE_KINDS = ['answer', 'clarification', 'plan'] as const

/**
 * Deterministic bounds on anything a model returns.
 *
 * A model is a remote process that can return a megabyte of nonsense, and every
 * field below is somewhere that could become an unbounded in-memory object.
 * These are limits on the *response*, not rules about what a task may contain —
 * the application's own limits still apply later.
 *
 * `options` matches `MAX_CHOICES` in `entityResolver`, because a clarification
 * is the same "which one did you mean?" question the command layer already asks
 * and the two lists should not disagree about how long that list may be.
 */
export const AI_LIMITS = {
  /** Checked before `JSON.parse`, so a huge string is refused without parsing. */
  rawResponse: 32_000,
  message: 2_000,
  options: 8,
  optionLength: 200,
  /**
   * Steps in one plan.
   *
   * A review limit rather than a technical one. A plan is confirmed as a whole,
   * so this is really "how many actions can a person read and take
   * responsibility for in one decision" — and past a handful, a confirmation
   * dialog stops being read and starts being clicked. Eight is generous for the
   * requests M15.8 exists for ("plan my evening", "organise my overdue work")
   * and small enough to stay legible in a chat message.
   */
  steps: 8,
  description: 200,
  /** A reference is a phrase like "Java revision", never a document. */
  query: 200,
  title: 500,
  /** A day. Generous for one task, and finite. */
  estimateMin: 24 * 60,
} as const
